application: sync-tweets
version: 1
runtime: python
api_version: 1

handlers:
- url: /feed(.*)
  script: feed.py

- url: /twitter(.*)
  script: twitter.py

- url: .*
  static_files : index.html
  upload: index.html
